#!/system/bin/sh

# Magisk Module: Systemless Debloater v1.5.2
# Copyright (c) zgfg @ xda, 2020-


# List of stock apps to be debloated by mounting dummy.apk through service.sh
# Generated by customize.sh when installing the module
# Do not edit

